version: '3'

services:
  laravel:
    build: 
      context: ../section-5
      dockerfile: Dockerfile.laravel
    image: retatu/laravel:prod
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    image: retatu/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge